# Titanic Missing Values

This notebook inspects missing values in the Titanic train and test datasets.

In [1]:
import pandas as pd

train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

def missing_summary(df, name):
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)
    print(f'\n{name} missing values:')
    display(missing.to_frame('missing_count'))

missing_summary(train, 'train')
missing_summary(test, 'test')

train missing values:

          missing_count
Cabin               687
Age                 177
Embarked              2

test missing values:

       missing_count
Cabin            327
Age               86
Fare               1

In [2]:
def impute_median_numeric(df):
    df = df.copy()
    numeric_cols = df.select_dtypes(include='number').columns
    for col in numeric_cols:
        if df[col].isna().any():
            df[col] = df[col].fillna(df[col].median())
    return df

train_imputed = impute_median_numeric(train)
test_imputed = impute_median_numeric(test)

print('Train missing after numeric median impute:', int(train_imputed.isna().sum().sum()))
print('Test missing after numeric median impute:', int(test_imputed.isna().sum().sum()))

Train missing after numeric median impute: 689
Test missing after numeric median impute: 327

In [ ]:
# Create a Cabin_deck feature (first letter) and preserve missingness as its own category.
# This avoids guessing a cabin value and lets models learn from the fact that it was not recorded.
train['Cabin_deck'] = train['Cabin'].str[0].fillna('Missing')
test['Cabin_deck'] = test['Cabin'].str[0].fillna('Missing')

print(train['Cabin_deck'].value_counts().head())

In [4]:
missing_summary(train_imputed, 'train')
missing_summary(test_imputed, 'test')

train missing values:

          missing_count
Cabin               687
Embarked              2

test missing values:

       missing_count
Cabin            327